version: '3.5'

services:
  #golang:
    #image: graph-backend
    #container_name: golang

    #ports:
      #- "8080:8080"

    #networks:
      #- prod

    #depends_on:
      #- "mysql"
      #- "neo4j"

  mysql:
    image: graph-db
    container_name: mysql

    expose:
      - '3306'
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: Graph
      MYSQL_USER: AdminUser
      MYSQL_PASSWORD: AdminPassword
      MYSQL_ROOT_HOST: 172.18.0.1

    volumes:
      - mysql:/var/lib/mysql

    networks:
      - prod

  neo4j:
    image: graph-neo4j
    container_name: neo4j

    environment:
      NEO4J_AUTH: "none"

    expose:
      - '7474'
      - '7687'

    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - neo4j:/neo4j/data

    networks:
      - prod

volumes:
  mysql:
  neo4j:

networks:
  prod:
    driver: bridge